"""
City configurations for street-sweeping data.

Each entry defines:
  name            Display name shown in the UI
  center          Default map center (lat/lon)
  manual_default  Fallback coordinates used when USE_LIVE_GPS = False
  local_path      Where the data file is cached on disk (relative to repo root)
  url             Download URL; None = file must be placed manually
  schema          Normalization schema key (handled by data_loader.py)
  bbox            Optional [lat_min, lon_min, lat_max, lon_max] clip after load

REGIONS groups cities geographically so the app can load several at once.
"""

CITIES = {
    # ------------------------------------------------------------------
    # Bay Area
    # ------------------------------------------------------------------
    "oakland": {
        "name": "Oakland, CA",
        "center": {"lat": 37.8044, "lon": -122.2712},
        "manual_default": {"lat": 37.821326, "lon": -122.280705},
        "local_path": "data/oakland/StreetSweeping.shp",
        # Bundled in the repo; no automatic download.
        "url": None,
        "schema": "oakland",
        "bbox": [37.69, -122.38, 37.90, -122.11],
        # Pre-normalised FlatGeobuf — built automatically on first load.
        "fgb_path": "data/oakland/StreetSweeping.fgb",
    },

    "san_francisco": {
        "name": "San Francisco, CA",
        "center": {"lat": 37.7749, "lon": -122.4194},
        "manual_default": {"lat": 37.7749, "lon": -122.4194},
        "local_path": "data/san_francisco/StreetSweeping.geojson",
        # DataSF – Street Sweeping Schedule (dataset yhqp-riqs)
        # The geospatial export endpoint returns 400; use the Socrata GeoJSON
        # resource API instead (supports up to ~200 k rows with $limit).
        "url": (
            "https://data.sfgov.org/resource/yhqp-riqs.geojson"
            "?$limit=200000"
        ),
        "schema": "sf",
        "bbox": [37.70, -122.53, 37.84, -122.35],
        # DataSF updates this dataset roughly monthly; refresh when file is older.
        "stale_after_days": 30,
        "fgb_path": "data/san_francisco/StreetSweeping.fgb",
    },

    "berkeley": {
        "name": "Berkeley, CA",
        "center": {"lat": 37.8716, "lon": -122.2727},
        "manual_default": {"lat": 37.8716, "lon": -122.2727},
        "local_path": "data/berkeley/StreetSweeping.geojson",
        # Generated by scripts/build_berkeley_geojson.py from the city's PDF schedules:
        # https://berkeleyca.gov/city-services/streets-sidewalks-sewers-and-utilities/street-sweeping
        # Run the script once (needs the PDFs in data/berkeley/) to produce the GeoJSON.
        "url": None,
        "schema": "berkeley",
        "bbox": [37.84, -122.32, 37.91, -122.23],
        "fgb_path": "data/berkeley/StreetSweeping.fgb",
    },

    "alameda": {
        "name": "Alameda, CA",
        "center": {"lat": 37.7652, "lon": -122.2416},
        "manual_default": {"lat": 37.7652, "lon": -122.2416},
        "local_path": "data/alameda/StreetSweeping.geojson",
        # Generated by scripts/build_alameda_geojson.py from the city's PDF schedule:
        # https://www.alamedaca.gov/Residents/Transportation-and-Streets/Street-Sweeping-Schedule
        # Save the PDF as data/alameda/street-sweeping-schedule.pdf, then run the script.
        "url": None,
        "schema": "alameda",
        "bbox": [37.73, -122.33, 37.79, -122.21],
        "fgb_path": "data/alameda/StreetSweeping.fgb",
    },

    "piedmont": {
        "name": "Piedmont, CA",
        "center": {"lat": 37.8240, "lon": -122.2335},
        "manual_default": {"lat": 37.8240, "lon": -122.2335},
        "local_path": "data/piedmont/StreetSweeping.geojson",
        # Piedmont has no public open-data portal for street sweeping.
        # Source: https://www.piedmont.ca.gov/departments/public_works/street_maintenance.php
        # Data must be built manually from the city's PDF schedule maps.
        # Schema likely matches Oakland (address-range segments with DAY_EVEN/ODD).
        "url": None,
        "schema": "oakland",
        "bbox": [37.815, -122.245, 37.835, -122.220],
        "fgb_path": "data/piedmont/StreetSweeping.fgb",
    },

    "emeryville": {
        "name": "Emeryville, CA",
        "center": {"lat": 37.8403, "lon": -122.2913},
        "manual_default": {"lat": 37.8403, "lon": -122.2913},
        "local_path": "data/emeryville/StreetSweeping.geojson",
        # Emeryville has no public shapefile for street sweeping as of 2026.
        # Source: https://www.emeryville.org/217/Street-Sweeping
        # Data must be built manually from the city's published schedule.
        # Schema likely matches Oakland (address-range segments with DAY_EVEN/ODD).
        "url": None,
        "schema": "oakland",
        "bbox": [37.825, -122.310, 37.855, -122.270],
        "fgb_path": "data/emeryville/StreetSweeping.fgb",
    },

    "santa_cruz": {
        "name": "Santa Cruz, CA",
        "center": {"lat": 36.9741, "lon": -122.0308},
        "manual_default": {"lat": 36.9741, "lon": -122.0308},
        "local_path": "data/santa_cruz/StreetSweeping.geojson",
        # Santa Cruz publishes street sweeping maps as PDFs.
        # Source: https://www.cityofsantacruz.com/government/city-departments/public-works/streets/street-sweeping
        # Data must be built manually from the city's zone maps.
        # Schema likely matches Oakland (address-range segments with DAY_EVEN/ODD).
        "url": None,
        "schema": "oakland",
        "bbox": [36.950, -122.070, 37.010, -121.990],
        "fgb_path": "data/santa_cruz/StreetSweeping.fgb",
    },

    # ------------------------------------------------------------------
    # Chicago
    # ------------------------------------------------------------------
    "san_jose": {
        "name": "San José, CA",
        "center": {"lat": 37.3382, "lon": -121.8863},
        "manual_default": {"lat": 37.3382, "lon": -121.8863},
        "local_path": "data/san_jose/StreetSweeping.geojson",
        # San José Open Data (Socrata) — search "street sweeping routes" at:
        #   https://data.sanjoseca.gov
        # The dataset is typically a GeoJSON or Shapefile with address-range
        # segments and day/time codes similar to Oakland.
        # Once the dataset ID is known, use:
        #   "https://data.sanjoseca.gov/resource/<DATASET_ID>.geojson?$limit=200000"
        "url": None,
        "schema": "oakland",
        "bbox": [37.18, -122.04, 37.47, -121.59],
        "fgb_path": "data/san_jose/StreetSweeping.fgb",
    },

    "fremont": {
        "name": "Fremont, CA",
        "center": {"lat": 37.5485, "lon": -121.9886},
        "manual_default": {"lat": 37.5485, "lon": -121.9886},
        "local_path": "data/fremont/StreetSweeping.geojson",
        # Fremont GIS open data — check:
        #   https://gis.fremont.gov/arcgis/rest/services/
        # or the city's public works page for a downloadable schedule shapefile.
        # Schema likely matches Oakland (address-range segments + DAY_EVEN/ODD).
        "url": None,
        "schema": "oakland",
        "bbox": [37.45, -122.09, 37.64, -121.86],
        "fgb_path": "data/fremont/StreetSweeping.fgb",
    },

    "san_leandro": {
        "name": "San Leandro, CA",
        "center": {"lat": 37.7249, "lon": -122.1561},
        "manual_default": {"lat": 37.7249, "lon": -122.1561},
        "local_path": "data/san_leandro/StreetSweeping.geojson",
        # San Leandro may publish data via Alameda County ArcGIS portal:
        #   https://www.acgov.org/acpw/index.html
        # Alternatively, the city's Public Works dept provides PDF maps:
        #   https://www.sanleandro.org/depts/pw/streets/sweeping.asp
        "url": None,
        "schema": "oakland",
        "bbox": [37.68, -122.20, 37.76, -122.11],
        "fgb_path": "data/san_leandro/StreetSweeping.fgb",
    },

    "hayward": {
        "name": "Hayward, CA",
        "center": {"lat": 37.6688, "lon": -122.0808},
        "manual_default": {"lat": 37.6688, "lon": -122.0808},
        "local_path": "data/hayward/StreetSweeping.geojson",
        # Hayward publishes a PDF street sweeping schedule by district:
        #   https://www.hayward-ca.gov/services/streets-parks/street-sweeping
        # Data needs to be digitized manually into a GeoJSON with address ranges.
        # Schema likely matches Oakland once digitized.
        "url": None,
        "schema": "oakland",
        "bbox": [37.61, -122.16, 37.73, -121.99],
        "fgb_path": "data/hayward/StreetSweeping.fgb",
    },

    # ------------------------------------------------------------------
    # Bay Area — cities requiring more research before adding
    # ------------------------------------------------------------------
    #
    # "marin_county": Marin County Open Data portal has some infrastructure data;
    #   individual cities (Novato, San Rafael) may have PDFs.
    #
    # "castro_valley": Alameda County unincorporated — check ACPW portal.
    #
    # ------------------------------------------------------------------
    # Chicago
    # ------------------------------------------------------------------
    "chicago_all": {
        "name": "Chicago, IL",
        "center": {"lat": 41.8781, "lon": -87.6298},
        "manual_default": {"lat": 41.9951, "lon": -87.6593},
        "local_path": "data/chicago/StreetSweepingZones.geojson",
        # Chicago Data Portal – Street Sweeping Zones (tabular dataset utb4-q645).
        # Includes polygon geometry AND sweeping schedule as month columns
        # (april..november).  Update the dataset ID each year when Chicago
        # publishes new data (typically March/April).
        # Delete data/chicago/StreetSweepingZones.geojson to force a re-download.
        "url": (
            "https://data.cityofchicago.org/resource/utb4-q645.geojson"
            "?$limit=50000"
        ),
        "schema": "chicago",
        # Full Chicago city limits
        "bbox": [41.644, -87.848, 42.024, -87.524],
        # Chicago publishes a new dataset each year (March/April); refresh annually.
        # Also update the dataset URL in this file when that happens.
        "stale_after_days": 90,
        "fgb_path": "data/chicago/StreetSweepingZones.fgb",
    },

}

# ---------------------------------------------------------------------------
# Regions – groups of cities loaded together when SINGLE_CITY_MODE = False
# ---------------------------------------------------------------------------

REGIONS = {
    "bay_area": {
        "name": "Bay Area",
        # Add piedmont/emeryville/santa_cruz here once their data files are built.
        "cities": ["oakland", "san_francisco", "berkeley", "alameda"],
        # Wider center / zoom used for the overview inset only
        "center": {"lat": 37.820, "lon": -122.295},
        "manual_default": {"lat": 37.821326, "lon": -122.280705},
        "overview_zoom": 9,
        "tz": "America/Los_Angeles",
    },
    "chicago": {
        "name": "Chicago",
        "cities": ["chicago_all"],
        # North Side default — shows Rogers Park / Edgewater / Uptown on load.
        "center": {"lat": 41.975, "lon": -87.660},
        "manual_default": {"lat": 41.996593, "lon": -87.665282},
        "overview_zoom": 13,
        "tz": "America/Chicago",
    },
}
